spring:
  profiles: temp

  servlet:
    multipart:
      max-file-size: 10MB #업로드 파일 사이즈 제한
      max-request-size: 10MB #업로드 파일 사이즈 제한

  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:mariadb://helloshop-db.ch30djhspsrg.ap-northeast-2.rds.amazonaws.com:3306/karrot
    username: admin
    password: ENC(BTbz4phZ3NL7xbMHNAE2LgBoAB3HXujL)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
  password: djifajdcznvkzc

#AWS 설정
cloud:
  aws:
    iam:
      access-key: ENC(Hi+Pynput2jHrHT0BGmk1TvNijKIlsgBrKh9SWMdVcQ=)
      secret-key: ENC(QrdVsRutSbWU90oHj3GybHkvTJF/W6d41L6Xvox1sS8eqmfLYE5WkpuIOsT+e9bqCwXHvrEY/Mw=)
    region:
      static: ap-northeast-2
    stack:
      auto: false

fcm:
  certification: /home/ec2-user/app/karrot/temp/karrot-38ab4-firebase-adminsdk-hnrb4-885ec63b2a.json