name: Deploy to Amazon EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      
      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash
        
      - name: Make zip file
        run: zip ./$GITHUB_SHA.zip build/libs/*.jar appspec.yml scripts/start.sh
        shell: bash
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ vars.AWS_BUCKET_NAME }}/$GITHUB_SHA.zip
      
      - name: Code Deploy
        run: aws deploy create-deployment --application-name karrot-clone --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name karrot-clone-deploy --s3-location bucket=${{ vars.AWS_BUCKET_NAME }},bundleType=zip,key=$GITHUB_SHA.zip
